name: Toolbox Unit Tests

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
          submodules: 'recursive'


    - name: Download Swift 6
      run: |
        curl -O https://download.swift.org/swift-6.0-release/xcode/swift-6.0-RELEASE/swift-6.0-RELEASE-osx.pkg
        sudo installer -pkg swift-6.0-RELEASE-osx.pkg -target /

    - name: Get swift version
      run: swift --version

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Run Tests
      run: |
        cd DocuBotToolbox/Sources/DocuBotToolbox
        swift test