name: Toolbox Unit Tests

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
          submodules: 'recursive'

    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: 6.0

    - name: Get swift version
      run: swift --version

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Run Tests
      run: |
        cd DocuBotToolbox/Sources/DocuBotToolbox
        swift test